### ISSUE TITLE
RSS_restricted в 4 пункте 4 задачи

### ISSUE THREAD

**Issue by Flatout73** [Sammers21/math_stat_python#27]
По-моему, когда мы считаем y_estimation_r мы должны брать не просто первые 2 коэффициента у модели, а перерассчитывать всю модель (т.е. новые коэффициенты) без учета двух последних X. Вопрос на обсуждение.

**Comment by isgulkov** [comment]
Если я правильно понял, про что это было написано, то по-моему, нет, мы должны просто приравнивать к-ты 3 и 4 к нулю, а 1 и 2 оставлять без изменений. Доказательство: так сделано у зака-хсе, а он эту задачу сдал.

```python
Y_restricted = [coefs[0] + coefs[1] * X2_sample[i]
                for i in range(len(X2_sample))]
```

**Comment by Flatout73** [comment]
Ну Фурмач особо не вчитывается в то, что ты сделал, поэтому иногда может принять неправильное решение. Просто так, как я написал, мы делали на семинаре, только тогда новые коэффициенты уже были даны, так как, по словам Фурмача, мы бы их долго сами считали.

**Comment by Flatout73** [comment]
Ну кароч можно ничего не исправлять, но если че, знайте, что надо было сделать так!

**Comment by Sammers21** [comment]
@Flatout73, Да, Лёна ты прав. Я помню что я хотел заново пересчитать модель. Мы долго это обсуждали с Сергеем. Я почему-то забыл это сделать. Ты прав. Нужно пересчитать модель в этом случае.

Сделаешь Pull Request?
