### ISSUE TITLE
Проверка гипотезы о значимости регресси в целом

### ISSUE THREAD

**Issue by Flatout73** [Sammers21/math_stat_python#31]
Кстати говоря, в проверки этой гипотезы не фигурирует свободный член B1. Фурмач на это бугуртит. Вместо b1=b2=b3=b4=0 надо писать b2=b3=b4=0.

**Comment by Sammers21** [comment]
@Flatout73 , инфа 100?

**Comment by Flatout73** [comment]
@Sammers21 да
